spring.application.name=news-line

## line bot:
line.bot.channel-token=${LINE_TOKEN}
line.bot.channel-secret=${LINE_SECRET}
line.bot.handler.path=/callback
line.bot.handler.enabled=true

## Scheduler configuration
line.user.id=${LINE_USERID}

